// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/api/configured-providers": {
    params: {};
  };
  "/api/system/diagnostics": {
    params: {};
  };
  "/api/mcp-update-config": {
    params: {};
  };
  "/api/runtime/terminal": {
    params: {};
  };
  "/api/system/disk-info": {
    params: {};
  };
  "/api/export-api-keys": {
    params: {};
  };
  "/api/github-branches": {
    params: {};
  };
  "/api/github-template": {
    params: {};
  };
  "/api/gitlab-branches": {
    params: {};
  };
  "/api/gitlab-projects": {
    params: {};
  };
  "/api/system/git-info": {
    params: {};
  };
  "/api/check-env-keys": {
    params: {};
  };
  "/api/netlify-deploy": {
    params: {};
  };
  "/api/runtime/search": {
    params: {};
  };
  "/api/vercel-domains": {
    params: {};
  };
  "/api/check-env-key": {
    params: {};
  };
  "/api/supabase-user": {
    params: {};
  };
  "/api/vercel-deploy": {
    params: {};
  };
  "/api/version-check": {
    params: {};
  };
  "/api/github-stats": {
    params: {};
  };
  "/api/netlify-user": {
    params: {};
  };
  "/api/runtime/exec": {
    params: {};
  };
  "/api/vercel-proxy": {
    params: {};
  };
  "/api/git-proxy/*": {
    params: {
      "*": string;
    };
  };
  "/api/github-user": {
    params: {};
  };
  "/api/runtime/git": {
    params: {};
  };
  "/api/vercel-user": {
    params: {};
  };
  "/api/bug-report": {
    params: {};
  };
  "/api/db/migrate": {
    params: {};
  };
  "/api/runtime/fs": {
    params: {};
  };
  "/api/web-search": {
    params: {};
  };
  "/api/git-clone": {
    params: {};
  };
  "/api/mcp-check": {
    params: {};
  };
  "/api/v1/status": {
    params: {};
  };
  "/preview/:port": {
    params: {
      "port": string;
    };
  };
  "/api/db/chats": {
    params: {};
  };
  "/api/db/chats/:id": {
    params: {
      "id": string;
    };
  };
  "/api/enhancer": {
    params: {};
  };
  "/api/git-info": {
    params: {};
  };
  "/api/supabase": {
    params: {};
  };
  "/api/supabase/variables": {
    params: {};
  };
  "/api/supabase/query": {
    params: {};
  };
  "/api/encrypt": {
    params: {};
  };
  "/api/llmcall": {
    params: {};
  };
  "/api/v1/chat": {
    params: {};
  };
  "/api/deploy": {
    params: {};
  };
  "/api/health": {
    params: {};
  };
  "/api/models": {
    params: {};
  };
  "/api/models/:provider": {
    params: {
      "provider": string;
    };
  };
  "/api/update": {
    params: {};
  };
  "/templates": {
    params: {};
  };
  "/api/chat": {
    params: {};
  };
  "/chat/:id": {
    params: {
      "id": string;
    };
  };
  "/git": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/api/configured-providers" | "/api/system/diagnostics" | "/api/mcp-update-config" | "/api/runtime/terminal" | "/api/system/disk-info" | "/api/export-api-keys" | "/api/github-branches" | "/api/github-template" | "/api/gitlab-branches" | "/api/gitlab-projects" | "/api/system/git-info" | "/api/check-env-keys" | "/api/netlify-deploy" | "/api/runtime/search" | "/api/vercel-domains" | "/api/check-env-key" | "/api/supabase-user" | "/api/vercel-deploy" | "/api/version-check" | "/api/github-stats" | "/api/netlify-user" | "/api/runtime/exec" | "/api/vercel-proxy" | "/api/git-proxy/*" | "/api/github-user" | "/api/runtime/git" | "/api/vercel-user" | "/api/bug-report" | "/api/db/migrate" | "/api/runtime/fs" | "/api/web-search" | "/api/git-clone" | "/api/mcp-check" | "/api/v1/status" | "/preview/:port" | "/api/db/chats" | "/api/db/chats/:id" | "/api/enhancer" | "/api/git-info" | "/api/supabase" | "/api/supabase/variables" | "/api/supabase/query" | "/api/encrypt" | "/api/llmcall" | "/api/v1/chat" | "/api/deploy" | "/api/health" | "/api/models" | "/api/models/:provider" | "/api/update" | "/templates" | "/api/chat" | "/chat/:id" | "/git" | "/*";
  };
  "routes/api.configured-providers.ts": {
    id: "routes/api.configured-providers";
    page: "/api/configured-providers";
  };
  "routes/api.system.diagnostics.ts": {
    id: "routes/api.system.diagnostics";
    page: "/api/system/diagnostics";
  };
  "routes/api.mcp-update-config.ts": {
    id: "routes/api.mcp-update-config";
    page: "/api/mcp-update-config";
  };
  "routes/api.runtime.terminal.ts": {
    id: "routes/api.runtime.terminal";
    page: "/api/runtime/terminal";
  };
  "routes/api.system.disk-info.ts": {
    id: "routes/api.system.disk-info";
    page: "/api/system/disk-info";
  };
  "routes/api.export-api-keys.ts": {
    id: "routes/api.export-api-keys";
    page: "/api/export-api-keys";
  };
  "routes/api.github-branches.ts": {
    id: "routes/api.github-branches";
    page: "/api/github-branches";
  };
  "routes/api.github-template.ts": {
    id: "routes/api.github-template";
    page: "/api/github-template";
  };
  "routes/api.gitlab-branches.ts": {
    id: "routes/api.gitlab-branches";
    page: "/api/gitlab-branches";
  };
  "routes/api.gitlab-projects.ts": {
    id: "routes/api.gitlab-projects";
    page: "/api/gitlab-projects";
  };
  "routes/api.system.git-info.ts": {
    id: "routes/api.system.git-info";
    page: "/api/system/git-info";
  };
  "routes/api.check-env-keys.ts": {
    id: "routes/api.check-env-keys";
    page: "/api/check-env-keys";
  };
  "routes/api.netlify-deploy.ts": {
    id: "routes/api.netlify-deploy";
    page: "/api/netlify-deploy";
  };
  "routes/api.runtime.search.ts": {
    id: "routes/api.runtime.search";
    page: "/api/runtime/search";
  };
  "routes/api.vercel-domains.ts": {
    id: "routes/api.vercel-domains";
    page: "/api/vercel-domains";
  };
  "routes/api.check-env-key.ts": {
    id: "routes/api.check-env-key";
    page: "/api/check-env-key";
  };
  "routes/api.supabase-user.ts": {
    id: "routes/api.supabase-user";
    page: "/api/supabase-user";
  };
  "routes/api.vercel-deploy.ts": {
    id: "routes/api.vercel-deploy";
    page: "/api/vercel-deploy";
  };
  "routes/api.version-check.ts": {
    id: "routes/api.version-check";
    page: "/api/version-check";
  };
  "routes/api.github-stats.ts": {
    id: "routes/api.github-stats";
    page: "/api/github-stats";
  };
  "routes/api.netlify-user.ts": {
    id: "routes/api.netlify-user";
    page: "/api/netlify-user";
  };
  "routes/api.runtime.exec.ts": {
    id: "routes/api.runtime.exec";
    page: "/api/runtime/exec";
  };
  "routes/api.vercel-proxy.ts": {
    id: "routes/api.vercel-proxy";
    page: "/api/vercel-proxy";
  };
  "routes/api.git-proxy.$.ts": {
    id: "routes/api.git-proxy.$";
    page: "/api/git-proxy/*";
  };
  "routes/api.github-user.ts": {
    id: "routes/api.github-user";
    page: "/api/github-user";
  };
  "routes/api.runtime.git.ts": {
    id: "routes/api.runtime.git";
    page: "/api/runtime/git";
  };
  "routes/api.vercel-user.ts": {
    id: "routes/api.vercel-user";
    page: "/api/vercel-user";
  };
  "routes/api.bug-report.ts": {
    id: "routes/api.bug-report";
    page: "/api/bug-report";
  };
  "routes/api.db.migrate.ts": {
    id: "routes/api.db.migrate";
    page: "/api/db/migrate";
  };
  "routes/api.runtime.fs.ts": {
    id: "routes/api.runtime.fs";
    page: "/api/runtime/fs";
  };
  "routes/api.web-search.ts": {
    id: "routes/api.web-search";
    page: "/api/web-search";
  };
  "routes/api.git-clone.ts": {
    id: "routes/api.git-clone";
    page: "/api/git-clone";
  };
  "routes/api.mcp-check.ts": {
    id: "routes/api.mcp-check";
    page: "/api/mcp-check";
  };
  "routes/api.v1.status.ts": {
    id: "routes/api.v1.status";
    page: "/api/v1/status";
  };
  "routes/preview.$port.tsx": {
    id: "routes/preview.$port";
    page: "/preview/:port";
  };
  "routes/api.db.chats.ts": {
    id: "routes/api.db.chats";
    page: "/api/db/chats" | "/api/db/chats/:id";
  };
  "routes/api.db.chats.$id.ts": {
    id: "routes/api.db.chats.$id";
    page: "/api/db/chats/:id";
  };
  "routes/api.enhancer.ts": {
    id: "routes/api.enhancer";
    page: "/api/enhancer";
  };
  "routes/api.git-info.ts": {
    id: "routes/api.git-info";
    page: "/api/git-info";
  };
  "routes/api.supabase.ts": {
    id: "routes/api.supabase";
    page: "/api/supabase" | "/api/supabase/variables" | "/api/supabase/query";
  };
  "routes/api.supabase.variables.ts": {
    id: "routes/api.supabase.variables";
    page: "/api/supabase/variables";
  };
  "routes/api.supabase.query.ts": {
    id: "routes/api.supabase.query";
    page: "/api/supabase/query";
  };
  "routes/api.encrypt.ts": {
    id: "routes/api.encrypt";
    page: "/api/encrypt";
  };
  "routes/api.llmcall.ts": {
    id: "routes/api.llmcall";
    page: "/api/llmcall";
  };
  "routes/api.v1.chat.ts": {
    id: "routes/api.v1.chat";
    page: "/api/v1/chat";
  };
  "routes/api.deploy.ts": {
    id: "routes/api.deploy";
    page: "/api/deploy";
  };
  "routes/api.health.ts": {
    id: "routes/api.health";
    page: "/api/health";
  };
  "routes/api.models.ts": {
    id: "routes/api.models";
    page: "/api/models" | "/api/models/:provider";
  };
  "routes/api.models.$provider.ts": {
    id: "routes/api.models.$provider";
    page: "/api/models/:provider";
  };
  "routes/api.update.ts": {
    id: "routes/api.update";
    page: "/api/update";
  };
  "routes/templates.tsx": {
    id: "routes/templates";
    page: "/templates";
  };
  "routes/api.chat.ts": {
    id: "routes/api.chat";
    page: "/api/chat";
  };
  "routes/chat.$id.tsx": {
    id: "routes/chat.$id";
    page: "/chat/:id";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/git.tsx": {
    id: "routes/git";
    page: "/git";
  };
  "routes/$.tsx": {
    id: "routes/$";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/api.configured-providers": typeof import("./app/routes/api.configured-providers.ts");
  "routes/api.system.diagnostics": typeof import("./app/routes/api.system.diagnostics.ts");
  "routes/api.mcp-update-config": typeof import("./app/routes/api.mcp-update-config.ts");
  "routes/api.runtime.terminal": typeof import("./app/routes/api.runtime.terminal.ts");
  "routes/api.system.disk-info": typeof import("./app/routes/api.system.disk-info.ts");
  "routes/api.export-api-keys": typeof import("./app/routes/api.export-api-keys.ts");
  "routes/api.github-branches": typeof import("./app/routes/api.github-branches.ts");
  "routes/api.github-template": typeof import("./app/routes/api.github-template.ts");
  "routes/api.gitlab-branches": typeof import("./app/routes/api.gitlab-branches.ts");
  "routes/api.gitlab-projects": typeof import("./app/routes/api.gitlab-projects.ts");
  "routes/api.system.git-info": typeof import("./app/routes/api.system.git-info.ts");
  "routes/api.check-env-keys": typeof import("./app/routes/api.check-env-keys.ts");
  "routes/api.netlify-deploy": typeof import("./app/routes/api.netlify-deploy.ts");
  "routes/api.runtime.search": typeof import("./app/routes/api.runtime.search.ts");
  "routes/api.vercel-domains": typeof import("./app/routes/api.vercel-domains.ts");
  "routes/api.check-env-key": typeof import("./app/routes/api.check-env-key.ts");
  "routes/api.supabase-user": typeof import("./app/routes/api.supabase-user.ts");
  "routes/api.vercel-deploy": typeof import("./app/routes/api.vercel-deploy.ts");
  "routes/api.version-check": typeof import("./app/routes/api.version-check.ts");
  "routes/api.github-stats": typeof import("./app/routes/api.github-stats.ts");
  "routes/api.netlify-user": typeof import("./app/routes/api.netlify-user.ts");
  "routes/api.runtime.exec": typeof import("./app/routes/api.runtime.exec.ts");
  "routes/api.vercel-proxy": typeof import("./app/routes/api.vercel-proxy.ts");
  "routes/api.git-proxy.$": typeof import("./app/routes/api.git-proxy.$.ts");
  "routes/api.github-user": typeof import("./app/routes/api.github-user.ts");
  "routes/api.runtime.git": typeof import("./app/routes/api.runtime.git.ts");
  "routes/api.vercel-user": typeof import("./app/routes/api.vercel-user.ts");
  "routes/api.bug-report": typeof import("./app/routes/api.bug-report.ts");
  "routes/api.db.migrate": typeof import("./app/routes/api.db.migrate.ts");
  "routes/api.runtime.fs": typeof import("./app/routes/api.runtime.fs.ts");
  "routes/api.web-search": typeof import("./app/routes/api.web-search.ts");
  "routes/api.git-clone": typeof import("./app/routes/api.git-clone.ts");
  "routes/api.mcp-check": typeof import("./app/routes/api.mcp-check.ts");
  "routes/api.v1.status": typeof import("./app/routes/api.v1.status.ts");
  "routes/preview.$port": typeof import("./app/routes/preview.$port.tsx");
  "routes/api.db.chats": typeof import("./app/routes/api.db.chats.ts");
  "routes/api.db.chats.$id": typeof import("./app/routes/api.db.chats.$id.ts");
  "routes/api.enhancer": typeof import("./app/routes/api.enhancer.ts");
  "routes/api.git-info": typeof import("./app/routes/api.git-info.ts");
  "routes/api.supabase": typeof import("./app/routes/api.supabase.ts");
  "routes/api.supabase.variables": typeof import("./app/routes/api.supabase.variables.ts");
  "routes/api.supabase.query": typeof import("./app/routes/api.supabase.query.ts");
  "routes/api.encrypt": typeof import("./app/routes/api.encrypt.ts");
  "routes/api.llmcall": typeof import("./app/routes/api.llmcall.ts");
  "routes/api.v1.chat": typeof import("./app/routes/api.v1.chat.ts");
  "routes/api.deploy": typeof import("./app/routes/api.deploy.ts");
  "routes/api.health": typeof import("./app/routes/api.health.ts");
  "routes/api.models": typeof import("./app/routes/api.models.ts");
  "routes/api.models.$provider": typeof import("./app/routes/api.models.$provider.ts");
  "routes/api.update": typeof import("./app/routes/api.update.ts");
  "routes/templates": typeof import("./app/routes/templates.tsx");
  "routes/api.chat": typeof import("./app/routes/api.chat.ts");
  "routes/chat.$id": typeof import("./app/routes/chat.$id.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/git": typeof import("./app/routes/git.tsx");
  "routes/$": typeof import("./app/routes/$.tsx");
};