export * from './types';

// Re-export protocol members except ScreenshotOptions (already exported from ./types)
export {
  INSPECTOR_COMMAND_TYPES,
  INSPECTOR_EVENT_TYPES,
  COMMAND_TYPE_SET,
  EVENT_TYPE_SET,
  MESSAGE_TYPE_SET,
  type InspectorCommandType,
  type InspectorEventType,
  type InspectorMessageType,
  type ActivateCommand,
  type EditStyleCommand,
  type EditTextCommand,
  type SelectBySelectorCommand,
  type RevertCommand,
  type BulkStyleCommand,
  type BulkRevertCommand,
  type CountElementsCommand,
  type CaptureScreenshotRequestCommand,
  type DeleteElementCommand,
  type InspectorCommand,
  type ReadyEvent,
  type HoverEvent,
  type LeaveEvent,
  type ClickEvent,
  type ResizeEvent,
  type ResizeEndEvent,
  type EditAppliedEvent,
  type TextAppliedEvent,
  type RevertedEvent,
  type BulkAppliedEvent,
  type BulkRevertedEvent,
  type ElementCountEvent,
  type ElementDeletedEvent,
  type ConsoleErrorEvent,
  type ViteErrorEvent,
  type ScreenshotResponseEvent,
  type InspectorEvent,
  type InspectorMessage,
  isInspectorEvent,
} from './protocol';
